name: Build Purswm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          
      - name: Grant execute permission for gradlew
        run: chmod +x Purpur/gradlew
        
      - name: Build with Gradle
        run: cd Purpur && ./gradlew build --no-daemon
        
      - name: Upload Server JAR
        uses: actions/upload-artifact@v4
        with:
          name: purswm-server
          path: Purpur/purpur-server/build/libs/*.jar
          
      - name: Upload API JAR
        uses: actions/upload-artifact@v4
        with:
          name: purswm-api
          path: Purpur/purpur-api/build/libs/*.jar
